AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MeetupHeaderRule:
    Type: AWS::WAFRegional::ByteMatchSet
    Properties:
      Name: 'ByteMatch for Workshop header'
      ByteMatchTuples:
        - FieldToMatch:
            Type: HEADER
            Data: 'x-from'
          PositionalConstraint: EXACTLY
          TextTransformation: LOWERCASE
          TargetString: awsworkshop
  BlackHatRule:
    Type: AWS::WAFRegional::ByteMatchSet
    Properties:
      Name: 'ByteMatch for Workshop header'
      ByteMatchTuples:
        - FieldToMatch:
            Type: HEADER
            Data: 'x-from'
          PositionalConstraint: EXACTLY
          TextTransformation: LOWERCASE
          TargetString: blackhathacker
  RuleMeetupRequest:
    Type: AWS::WAFRegional::Rule
    Properties:
      MetricName: MeetupRequest
      Name: MeetupRequest
      Predicates:
      - DataId: !Ref MeetupHeaderRule
        Negated: False
        Type: ByteMatch
  RuleBlackHatRequest:
    Type: AWS::WAFRegional::Rule
    Properties:
      MetricName: BlackHatRequest
      Name: BlackHatRequest
      Predicates:
      - DataId: !Ref BlackHatRule
        Negated: False
        Type: ByteMatch
  MeetupAcl:
    Type: AWS::WAFRegional::WebACL
    Properties:
      DefaultAction:
        Type: 'ALLOW'
      MetricName: MeetupWorkshopRequests
      Name: 'WEB ACL For Meetup Workshop'
      Rules:
       - Action: 
           Type: COUNT
         Priority: 100
         RuleId: !Ref RuleMeetupRequest
       - Action: 
           Type: BLOCK
         Priority: 200 
         RuleId: !Ref RuleBlackHatRequest
    