AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: endpoint.handler
      Runtime: python3.7
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/helloworld'
            Method: get
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
Outputs:
  Endpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/helloworld"
  ApiGateway:
    Value: !Ref ServerlessRestApi
    Export:
      Name: AWSToolsAndProgrammingDEC19API